### ISSUE TITLE
Issue: Switching from Edit Tags, to Quick Tags doesn't remember place

### ISSUE THREAD

**Issue by dlectronique** [Marekkon5/onetagger#103] opened 2022-04-22 22:42 UTC
I'm currently in the process of tagging a big ol' library of tracks. I'm doing this in Quick Tag, sorted on artist.  If I want to edit a bad imported tag, I switch to Edit Tag to make the change, but when I go back to Quick Tag, it doesn't remember the order preference (changes pack to sort on title). Also when I scroll all the way back to my progress, sometimes using up/down key makes the view jump 10 songs down. Restarting the program helps. I've had this a few times now in the last couple of hours, so I figured I'd raise an issue :)

I'm using the latest version, on Windows 10.

**Comment by dlectronique** [comment] 2022-04-22 22:47
Ok, correction - I've tried restarting the program a couple of times, and it drops me like a good 6 times scrolling of songs below the highlighted/selected song

**Comment by dlectronique** [comment] 2022-04-22 23:11
Apologies for the multi comment - but upon further inspection, the program seems to behave normally if I scroll all the way to where I was and then click on the song.

It also seems like the tags for a handful of songs repeatedly get erased, but this is only for a handful of tracks.

Thanks in advance for your help :) I am really digging the program overall

**Comment by Marekkon5** [comment] 2022-04-23 12:09
Hello, I've fixed the scrolling issue and the QT scroll position persistance in the latest commit. You can get the binary from the Actions tab to try it out. Let me know if it works for you. 

As for the tags getting erased - I'll need log and ideally also one example file where it happen so I can try myself and reproduce and find the issue. Thanks

**Comment by dlectronique** [comment] 2022-04-23 12:35
Hi there, thank you so much for your incredibly swift support! Could you let me know how to get the logs and the file to you?

Once I've sent you that, I will try the new binary.

**Comment by Marekkon5** [comment] 2022-04-23 12:48
Open Settings in OneTagger, click the General tab and there Open Data Folder. There should be onetagger.log file which you can send here. Thanks

**Comment by dlectronique** [comment] 2022-04-23 13:01
If i click the open data folder button, it doesn't go anywhere.. Could you share the path of where it should be?

**Comment by dlectronique** [comment] 2022-04-23 13:04
[onetagger.log](https://github.com/Marekkon5/onetagger/files/8546968/onetagger.log)
ok, restarting it helped! here's the logs, for posterity i added a 'test' tag and restarted the program just before sending this

**Comment by dlectronique** [comment] 2022-04-23 13:10
https://drive.google.com/file/d/160gsYAa9Mfvicgdok7CXvTuujy8Bq81R/view?usp=sharing 
![onetagger_xhrUSAu3nb](https://user-images.githubusercontent.com/23238958/164895889-20e998b4-5233-4da3-9f1a-febf0d8516e9.png)

Uploaded one test file to my google drive, and the screengrab is from what it keeps returning to

--

I've also tried the new binary, and indeed the place persists now, although for some reason i need to scroll up and down to actually see where i am. not sure why that is happening

![image](https://user-images.githubusercontent.com/23238958/164895938-b1ffe916-137d-4695-8367-9966b9cd2052.png)

**Comment by Marekkon5** [comment] 2022-04-23 14:29
1. The scrolling - I can't really reproduce it. Do you have some exact steps which cause the effect every time? I've made another commit which might fix it, or might not. I can't really fix without reproducing.
2. The song - it seems to be a weird bug with the ID3 library 1T is using. I'll look into it later. There is no info in log or any error messages.

**Comment by dlectronique** [comment] 2022-04-23 14:42
>1. The scrolling - I can't really reproduce it. Do you have some exact steps which cause the effect every time? I've made another commit which might fix it, or might not. I can't really fix without reproducing.

When I'm in quick tag, notice a bad imported metadata tag that needs to be deleted, swap to edit tags to remove it, swap back and it remembers the place in the list, but sometimes it just doesn't show the tiles. Scrolling in and out of view helps 🤷🏻  It doesn't happen every time though.

>2. The song - it seems to be a weird bug with the ID3 library 1T is using. I'll look into it later. There is no info in log or any error messages.

There's like a handful of songs that it keeps happening to, but in all honesty, some of these tracks I've had for over 10 years and they have moved from computer to computer, to back up drives, who knows what kind of bad metadata has been included haha

**Comment by dlectronique** [comment] 2022-04-23 14:45
Not sure if you would like me to open a separate feature request for this, but it would be super helpful if the player keeps on the screen when swapping to edit tags, and perhaps has that track up in the tree view on the left for easier access. 

I have been absolutely loving using 1T, it's literally been the dj companion program i've been looking for. I've been advocating for it among all my dj friends too haha

**Comment by dlectronique** [comment] 2022-04-23 14:54
Sorry I keep bombarding you with things I find, but I occasionally get this error. I think it's because a track errored on matching. 1T still allows me to add tags even if it doesn't play the song within the program. Anything you could do to still allow it to play?

![image](https://user-images.githubusercontent.com/23238958/164911240-865d2ac5-ede2-4bf8-9d8a-75686c1d86fe.png)

**Comment by Marekkon5** [comment] 2022-04-23 15:07
1. The instruments tag - you can drag and drop the values in settings and order them alphabetically or in any way you want. 
2. The `Unexpected frame` - well the audio decoding libraries are pretty strict and you have invalid frame in your file. While most players will probably play it fine, the file is technically corrupted and I would have to find some library that can ignore those kinds of errors. However there is a bunch of tools that can repair those files. @bascurtiz will link them when he's available.

**Comment by dlectronique** [comment] 2022-04-23 15:13
> 1. The instruments tag - you can drag and drop the values in settings and order them alphabetically or in any way you want.
oh! i didn't know that was possible 😄 my instrument tag list is quite long and they fall of the page now :(

> The Unexpected frame - well the audio decoding libraries are pretty strict and you have invalid frame in your file. While most players will probably play it fine, the file is technically corrupted and I would have to find some library that can ignore those kinds of errors. However there is a bunch of tools that can repair those files. @bascurtiz will link them when he's available.

ok no problem, i'll wait for him to come online :)

Thanks!

**Comment by Marekkon5** [comment] 2022-04-23 17:21
In the latest commit I've added player to the Edit Tags section (you have to enable it in settings first under General). I've also added one more patch for the scroll thing, let me know if it helps. Thanks

**Comment by dlectronique** [comment] 2022-04-23 17:28
Awesome, thank you so much - the ET player build is still running, will try soon

**Comment by dlectronique** [comment] 2022-04-23 17:42
That works like a charm! Looks like the scroll thing behaves a bit better now too 🥳

**Comment by onetagger** [comment] 2022-04-23 18:03
> Sorry I keep bombarding you with things I find, but I occasionally get this error. I think it's because a track errored on matching. 1T still allows me to add tags even if it doesn't play the song within the program. Anything you could do to still allow it to play?
> 
> ![image](https://user-images.githubusercontent.com/23238958/164911240-865d2ac5-ede2-4bf8-9d8a-75686c1d86fe.png)

Hi!
These audo files are prolly corrupt one way or another. You can check them by dropping them into AudioTester64, which you can download here: http://www.vuplayer.com/other.php

To fix them, it might be possible using the article of Native Instruments here: https://support.native-instruments.com/hc/en-us/articles/209552929

**Comment by bascurtiz** [comment] 2022-04-23 18:03
> Sorry I keep bombarding you with things I find, but I occasionally get this error. I think it's because a track errored on matching. 1T still allows me to add tags even if it doesn't play the song within the program. Anything you could do to still allow it to play?
> 
> ![image](https://user-images.githubusercontent.com/23238958/164911240-865d2ac5-ede2-4bf8-9d8a-75686c1d86fe.png)

Hi!
These audo files are prolly corrupt one way or another. You can check them by dropping them into AudioTester64, which you can download here: http://www.vuplayer.com/other.php

To fix them, it might be possible using the article of Native Instruments here: https://support.native-instruments.com/hc/en-us/articles/209552929

**Comment by dlectronique** [comment] 2022-04-23 18:06
> > Sorry I keep bombarding you with things I find, but I occasionally get this error. I think it's because a track errored on matching. 1T still allows me to add tags even if it doesn't play the song within the program. Anything you could do to still allow it to play?
> > ![image](https://user-images.githubusercontent.com/23238958/164911240-865d2ac5-ede2-4bf8-9d8a-75686c1d86fe.png)
> 
> Hi! These audo files are prolly corrupt one way or another. You can check them by dropping them into AudioTester64, which you can download here: http://www.vuplayer.com/other.php
> 
> To fix them, it might be possible using the article of Native Instruments here: https://support.native-instruments.com/hc/en-us/articles/209552929

Thank you @bascurtiz - will have a look at this when i get a moment :)

**Comment by dlectronique** [comment] 2022-04-23 18:21
I noticed another thing in QT now - if you select a mood for a track, and then click another one to change it, instead of changing to the new value, it 'unselects' the current value

**Comment by bascurtiz** [comment] 2022-04-23 18:24
Yeah, prolly to do with that latest integration of the fact, mood couldn't be deleted. If you use the key binds it works fine. I bet @Marekkon5 can solve it, but he's taking a break at the moment.

**Comment by dlectronique** [comment] 2022-04-23 18:25
Oh no rush, just something I noticed 😄 I'm already super grateful with how responsive you both are

**Comment by Marekkon5** [comment] 2022-04-23 19:21
Should be fixed in the latest commit.

**Comment by dlectronique** [comment] 2022-04-23 19:47
That is indeed fixed! Thanks @Marekkon5 - also worth noting that the list progress persists even after updating the program, which is great! Really super helpful, thanks again

**Comment by Marekkon5** [comment] 2022-04-23 20:17
Feel free to comment or open another issue if you have more problems. Thanks

**Closed by Marekkon5** 2022-04-23 20:17 UTC
