### ISSUE TITLE
manual tagger currently has only a empty window

### ISSUE THREAD

**Issue by derzw3rg** [Marekkon5/onetagger#265] opened 2023-08-23 15:56 UTC
got the yesterday released and today patched build but sadly i only get an empty window when i rightclick and select "manual tag"

![image](https://github.com/Marekkon5/onetagger/assets/136205073/8b3c411c-c38a-400a-a905-4df007fe09d5)

**Comment by Marekkon5** [comment] 2023-08-23 19:03
1. It uses AutoTag config, do you have some platforms selected there?
2. Could you please send the log? 

Thanks

**Comment by Marekkon5** [comment] 2023-08-23 20:22
The latest commit introduced more info, errors list, and config from AT. Please try that build. Thanks

**Comment by Marekkon5** [comment] 2023-08-23 21:03
What platforms do you have selected? Can you provide artist + title? Can you send screenshot? Thanks

**Comment by Marekkon5** [comment] 2023-08-23 21:58
Once you click that start button it should start spinning and show results or list of errors.
If it doesnt work I'll try to reproduce tomorrow with your track.
+ Also the latest commit does log a bit more so you could try that.

**Comment by Marekkon5** [comment] 2023-08-24 10:07
Huh that's extremely weird, right click works fine for me in build and in chromium on Linux. But will probably add a button or shortcut.

**Comment by Marekkon5** [comment] 2023-08-24 20:39
The error 10004 is mostly there and can be ignored, shouldn't affect it. Will wait for screen recording, thanks

**Comment by Marekkon5** [comment] 2023-08-24 20:52
Sorry for all this, should be really fixed in the latest commit now.

**Comment by Marekkon5** [comment] 2023-08-24 21:49
Hello, 
1. I accidentally didn't show the version, so those might've been different versions as well + fixed the Beatport match without version.
2. Deduplicated all results in latest commit, HOWEVER the ISRC/ID matches might still be duplicated (ISRC + normal match) since they internally are different, even tho they point to the same track.

Let me know if it works for you. Thanks

**Closed** 2023-08-25 08:31 UTC
